name: Build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository contents
        uses: actions/checkout@v1

      - name: Install depencencies
        run: npm ci

      - name: Build
        run: npm run build
